#!/bin/sh

### BEGIN INIT INFO
# Provides:          Imperium
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Imperium at boot time
# Description:       Start Imperium at boot time
### END INIT INFO

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

case "$1" in

start)		echo "Starting Imperium... "
		nohup /usr/local/lib/imperium/servers/startimpscreen > /usr/local/lib/imperium/ImpServScreen.log&
		sleep 4
		echo "Starting TelImp... "
		nohup /usr/local/lib/imperium/clients/starttelimpscreen >  /usr/local/lib/imperium/TelImpScreen.log&
		;;
stop)		echo "Can not stop Imperium with this script... "
		exit 1
		;;
*)		echo "Usage: $0 start"
		exit 1
		;;
esac
exit 0
