#!/bin/sh

### BEGIN INIT INFO
# Provides:          Imperium
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Imperium at boot time
# Description:       Start Imperium at boot time
### END INIT INFO

case "$1" in

start)		echo "Starting Imperium... "
		nohup /etc/init.d/startimpscreen > /usr/local/lib/imperium/ImpServScreen.log&
		sleep 4
		echo "Starting TelImp... "
		nohup /etc/init.d/starttelimpscreen >  /usr/local/lib/imperium/TelImpScreen.log&
		;;
stop)		echo "Can not stop Imperium with this script... "
		exit 1
		;;
*)		echo "Usage: $0 start"
		exit 1
		;;
esac
exit 0
