#!/bin/sh

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

while :
do
cd /usr/local/lib/imperium/data
running=`ps ax|grep ImpServ|grep -v grep`
if [ -z "$running" ]; then
       # The Log Entry
       TIME="ImpServ Down, Restarting: `date +"%A, %B %d - %r"`"
       echo $TIME >>/usr/local/lib/imperium/ImpServ.log
	cd /usr/local/lib/imperium/data
       screen -fa -S ImpServ -d -U -m ../servers/ImpServ
fi
       sleep 600
done
exit 0
